version: 2.0

jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers

    working_directory: ~/automata
    steps:
      - checkout
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: composer pipeline