version: 2.1

orbs:
  php: circleci/php@1.1

jobs:
  build:
    executor: 
      name: php/default
      tag: 8.0
    steps:
      - checkout
      - php/install-packages
      - run: composer pipeline