version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:8.0-node-browsers
    steps:
      - checkout
      - run: sudo docker-php-ext-install zip
      - run: sudo composer self-update
      - run: composer install -n --prefer-dist
      - run: composer pipeline
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

